apiVersion: v1
kind: Service
metadata:
  name: kflake
  labels:
    app: kflake
spec:
  ports:
    - port: 3080
      name: kflake
  clusterIP: None
  selector:
    app: kflake
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kflake
spec:
  selector:
    matchLabels:
      app: kflake
  serviceName: kflake
  replicas: 3
  revisionHistoryLimit: 10
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kflake
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: kflake
        image: digiverse/kflake:0.1.1
        imagePullPolicy: Always
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 3080
          name: kflake  
        readinessProbe:
            httpGet:
              path: /status
              port: kflake
            initialDelaySeconds: 5
            periodSeconds: 60